In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.drop(columns=["Cabin"],inplace = True)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [ ]:
df["Age"].fillna(df["Age"].median(),inplace=True)

/tmp/ipykernel_4019/860536840.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

In [ ]:
df["Embarked"].fillna(df["Embarked"].mode()[0],inplace = True)

/tmp/ipykernel_4019/2929921552.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Embarked"].fillna(df["Embarked"].mode()[0],inplace = True)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
for column in df.columns:
  missing = df[column].isnull().sum()
  if missing > 0:
    print(column, "has missing values:" ,missing)
  else:
    print(column,"has no missing values")

PassengerId has no missing values
Survived has no missing values
Pclass has no missing values
Name has no missing values
Sex has no missing values
Age has no missing values
SibSp has no missing values
Parch has no missing values
Ticket has no missing values
Fare has no missing values
Embarked has no missing values

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

In [ ]:
for column in df.columns:
    missing = df[column].isnull().sum()

    if missing > 0:
        print("\nColumn:", column)
        print("Missing values:", missing)

        if df[column].dtype == "object":
            print("Suggestion: Fill with MODE (categorical data)")
        else:
            print("Suggestion: Fill with MEDIAN (numeric data)")

Column: Age
Missing values: 177
Suggestion: Fill with MEDIAN (numeric data)

Column: Cabin
Missing values: 687
Suggestion: Fill with MODE (categorical data)

Column: Embarked
Missing values: 2
Suggestion: Fill with MODE (categorical data)

In [ ]:
for column in df.columns:
    missing = df[column].isnull().sum()
    total = len(df)
    missing_percent = (missing / total) * 100

    if missing > 0:
        print("\nColumn:", column)
        print("Missing values:", missing)
        print("Missing %:", round(missing_percent, 2))

        if missing_percent > 50:
            print("Suggestion: DROP column (too many missing values)")
        elif df[column].dtype == "object":
            print("Suggestion: Fill with MODE")
        else:
            print("Suggestion: Fill with MEDIAN")

Column: Age
Missing values: 177
Missing %: 19.87
Suggestion: Fill with MEDIAN

Column: Cabin
Missing values: 687
Missing %: 77.1
Suggestion: DROP column (too many missing values)

Column: Embarked
Missing values: 2
Missing %: 0.22
Suggestion: Fill with MODE

In [1]:
import pandas as pd

def load_data(path):
    df = pd.read_csv(path)
    return df

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = load_data(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
def check_missing_values(df):
    return df.isnull().sum()
check_missing_values(df)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
def suggest_cleaning(df):
    for column in df.columns:
        missing = df[column].isnull().sum()
        total = len(df)
        missing_percent = (missing / total) * 100

        if missing > 0:
            print("\n--------------------------------------")
            print("Column:", column)
            print("Missing values:", missing)
            print("Missing %:", round(missing_percent, 2))

            if missing_percent > 50:
                print("Suggestion: DROP column")
            elif df[column].dtype == "object":
                print("Suggestion: Fill with MODE")
            else:
                print("Suggestion: Fill with MEDIAN")

In [7]:
suggest_cleaning(df)

--------------------------------------
Column: Age
Missing values: 177
Missing %: 19.87
Suggestion: Fill with MEDIAN

--------------------------------------
Column: Cabin
Missing values: 687
Missing %: 77.1
Suggestion: DROP column

--------------------------------------
Column: Embarked
Missing values: 2
Missing %: 0.22
Suggestion: Fill with MODE

In [8]:
import pandas as pd

def load_data(path):
    df = pd.read_csv(path)
    return df

def check_missing_values(df):
    return df.isnull().sum()

def suggest_cleaning(df):
    for column in df.columns:
        missing = df[column].isnull().sum()
        total = len(df)
        missing_percent = (missing / total) * 100

        if missing > 0:
            print("\n==============================")
            print("Column:", column)
            print("Missing values:", missing)
            print("Missing %:", round(missing_percent, 2))

            if missing_percent > 50:
                print("Suggestion: DROP column")
            elif df[column].dtype == "object":
                print("Suggestion: Fill with MODE")
            else:
                print("Suggestion: Fill with MEDIAN")

#here it is used to Run everything
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = load_data(url)

print("Missing Values:\n", check_missing_values(df))

print("\nCleaning Suggestions:")
suggest_cleaning(df)

Missing Values:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Cleaning Suggestions:

==============================
Column: Age
Missing values: 177
Missing %: 19.87
Suggestion: Fill with MEDIAN

==============================
Column: Cabin
Missing values: 687
Missing %: 77.1
Suggestion: DROP column

==============================
Column: Embarked
Missing values: 2
Missing %: 0.22
Suggestion: Fill with MODE

In [21]:
def auto_clean_data(df):

    df = df.copy()

    for column in df.columns:
        missing = df[column].isnull().sum()
        total = len(df)
        missing_percent = (missing / total) * 100

        if missing > 0:

            if missing_percent > 50:
                print(f"Dropping column: {column}")
                df.drop(columns=[column], inplace=True)

            elif df[column].dtype == "object":
                print(f"Filling {column} with MODE")
                df[column] = df[column].fillna(df[column].mode()[0])

            else:
                print(f"Filling {column} with MEDIAN")
                df[column] = df[column].fillna(df[column].median())

    return df

In [22]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = load_data(url)

cleaned_df = auto_clean_data(df)

cleaned_df.isnull().sum()

Filling Age with MEDIAN
Dropping column: Cabin
Filling Embarked with MODE

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [11]:
cleaned_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [15]:
cleaned_df = auto_clean_data(df)
cleaned_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [16]:
cleaned_df.to_csv("cleaned_titanic.csv", index=False)

In [17]:
from google.colab import files
files.download("cleaned_titanic.csv")

In [18]:
print("Before Cleaning:", df.shape)
print("After Cleaning:", cleaned_df.shape)

Before Cleaning: (891, 11)
After Cleaning: (891, 11)

In [19]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

original_df = load_data(url)
cleaned_df = auto_clean_data(original_df)

print("Before Cleaning:", original_df.shape)
print("After Cleaning:", cleaned_df.shape)

Filling Age with MEDIAN
Dropping column: Cabin
Filling Embarked with MODE
Before Cleaning: (891, 12)
After Cleaning: (891, 11)

/tmp/ipykernel_5814/3527910830.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].median(), inplace=True)
/tmp/ipykernel_5814/3527910830.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mode()[0], inplace=True)

In [23]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

original_df = load_data(url)
cleaned_df = auto_clean_data(original_df)

print("Before Cleaning:", original_df.shape)
print("After Cleaning:", cleaned_df.shape)

Filling Age with MEDIAN
Dropping column: Cabin
Filling Embarked with MODE
Before Cleaning: (891, 12)
After Cleaning: (891, 11)

In [24]:
def cleaning_report(original_df, cleaned_df):
    print("\n===== CLEANING REPORT =====")

    print("\nOriginal Shape:", original_df.shape)
    print("Cleaned Shape:", cleaned_df.shape)

    print("\nMissing Values After Cleaning:")
    print(cleaned_df.isnull().sum())
cleaning_report(original_df, cleaned_df)

===== CLEANING REPORT =====

Original Shape: (891, 12)
Cleaned Shape: (891, 11)

Missing Values After Cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64